// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iosxhlvszjltgifapjag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvc3hobHZzempsdGdpZmFwamFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzQwNzUsImV4cCI6MjA2Mzc1MDA3NX0.4kMF7nmhCE5JvdRZcpYJdU-Blc_IqghgXShDFXnGU0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);